name: Taupunktlueftung
services:
  raven:
    image: ravendb/ravendb
    restart: always
    environment:
      RAVEN_SETTINGS: "{}"
      RAVEN_Setup_Mode: None
      RAVEN_Security_UnsecuredAccessAllowed: PublicNetwork
      RAVEN_ServerUrl: http://0.0.0.0:8080
    ports:
      - 38888:38888
      - 8080:8080
      - 53700:53700
    volumes:
      - raven_data:/var/lib/ravendb/data

volumes:
  raven_data:
