services:
  mongo:
    image: mongo:4.4.18
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: YOURUSERNAME
      MONGO_INITDB_ROOT_PASSWORD: YOURPASS
    volumes:
      - ./db:/data/db
    ports:
      - "27017:27017"

  raven:
    image: ravendb/ravendb:ubuntu-latest
    restart: always

    ports:
      - 38888:38888
      - 8080:8080
      - 53700:53700
    volumes:
      - ./raven/config:/etc/ravendb
      - raven_data:/var/lib/ravendb/data

volumes:
  raven_data:
